import type { Json } from "./api";
import { deepEqual, getPath, setPath } from "./utils";

/**
 * The top preset bar.
 *
 * `tracking.preset` is a claim about the config, not a memory of which button was clicked
 * last: `naming.run_tags` tags the run with it, and the Compare tab filters and groups by
 * it. So it is re-derived after every edit and given up the moment the config stops
 * matching — the bar's highlight reads the same answer, and cannot outlive the config it
 * describes either. The preset configs come from the server (`GET /api/presets`,
 * generated by `apply_preset` in trainlab/presets.py), which demotes a stale label the
 * same way on its side, so the two cannot disagree about what `balanced` means.
 */

export interface PresetDef {
  key: string;
  label: string;
  description: string;
  config: Json;
}

export const PRESET_PATH = "tracking.preset";
export const CUSTOM_PRESET = "custom";

/**
 * The fields a preset does not describe. Applying one keeps them, and changing one costs
 * no label: where the data lives and where output goes, what the app auto-detects for you
 * (`num_classes`/`class_names`), and the whole `tracking` group — which says where a run
 * is recorded rather than how it trains, and holds the label being derived.
 *
 * Mirrors `PRESET_IDENTITY_FIELDS` in trainlab/presets.py; keep the two in step.
 */
export const PRESET_IDENTITY_FIELDS = [
  "schema_version",
  "data.train_dir", "data.val_dir", "data.num_classes", "data.class_names",
  "checkpoint.output_dir", "checkpoint.resume_from",
  "tracking",
];

/** Config with `p` applied: its values everywhere except the fields above. */
export function applyPreset(config: Json, p: PresetDef): Json {
  let next: Json = { ...p.config };
  for (const path of PRESET_IDENTITY_FIELDS) {
    const kept = getPath(config, path);
    if (kept !== undefined) next = setPath(next, path, kept);
  }
  return setPath(next, PRESET_PATH, p.key);
}

/**
 * The preset this config still is, or `custom`.
 *
 * "Still is" means applying it again would change nothing, so the bar can never highlight
 * a button that would move the form if you pressed it. Demotion only, matching
 * `TrainConfig._demote_stale_preset`: a config that merely happens to equal a preset is
 * not retitled behind the user's back.
 */
export function derivePreset(config: Json, presets: PresetDef[]): string {
  const p = presets.find((x) => x.key === getPath(config, PRESET_PATH));
  return p && deepEqual(config, applyPreset(config, p)) ? p.key : CUSTOM_PRESET;
}

/** The config with `tracking.preset` re-derived. Every edit in the form goes through it. */
export function withDerivedPreset(config: Json, presets: PresetDef[]): Json {
  return setPath(config, PRESET_PATH, derivePreset(config, presets));
}
